spring:
  application:
    name: project-patory

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/petory?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul}
    username: ${SPRING_DATASOURCE_USERNAME:petoryuser}
    password: ${SPRING_DATASOURCE_PASSWORD:petorypassword}
    driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  secret: ${JWT_SECRET:default_jwt_secret_key_for_local_development_environment}

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    s3:
      bucket: ${AWS_S3_BUCKET_NAME}
    region:
      static: ap-northeast-2